### ISSUE TITLE
Implement support for encrypted private keys?

### ISSUE THREAD

**Issue by maxg203** [snowflakedb/snowflake-ingest-python#30]
From the source code in this repository, I cannot see any way for us to use our encrypted private keys with Snowpipe. The error is very helpful however (from `openssl`, one of your dependencies).

It would be nice to be prompted for a password, so that we could use encrypted keys too, particularly for easier testing and rapid development.

Trying to run your example with my private key gives the following Python error:
```
Traceback (most recent call last):
  File "snowpipe.py", line 58, in <module>
    resp = ingest_manager.ingest_files(staged_file_list)
  File "/usr/local/lib/python3.7/site-packages/snowflake/ingest/simple_ingest_manager.py", line 120, in ingest_files
    headers = self._get_headers()
  File "/usr/local/lib/python3.7/site-packages/snowflake/ingest/simple_ingest_manager.py", line 99, in _get_headers
    headers = self._get_auth_header()
  File "/usr/local/lib/python3.7/site-packages/snowflake/ingest/simple_ingest_manager.py", line 84, in _get_auth_header
    token_bearer = BEARER_FORMAT.format(self.sec_manager.get_token())
  File "/usr/local/lib/python3.7/site-packages/snowflake/ingest/utils/tokentools.py", line 83, in get_token
    self.token = jwt.encode(payload, self.private_key, algorithm=SecurityManager.ALGORITHM)
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 65, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jws.py", line 113, in encode
    key = alg_obj.prepare_key(key)
  File "/usr/local/lib/python3.7/site-packages/jwt/algorithms.py", line 205, in prepare_key
    key = load_pem_private_key(key, password=None, backend=default_backend())
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1051, in load_pem_private_key
    password,
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1268, in _load_key
    "Password was not given but private key is encrypted"
TypeError: Password was not given but private key is encrypted
```

**Comment by howryu** [comment]
Hi @maxg203,
It is by design that we did not take encrypted private key. The reasoning behind this is that application should keep private key password safe. As a programming library, snowflake-ingest-python will take unencrypted private key. You as the application developer, needs to write some code to decrypt your encrypted private key and pass it to the library.

**Comment by maxg203** [comment]
Ah okay, that makes sense and thank you for the clarification @howryu. I'll do that.
